import Hent_Footer from "./hent_logo.svg";
import Facebook from "./facebook.svg";
import Instagram from "./instagram.svg";
import Youtube from "./youtube.svg";
import Hent from "./hent.svg";
import IconLosangle from "./IconLosangle.svg";
import Poligono from "./poligono.svg";
import Newspaper from "./newspaper.svg";
import Key from "./key.svg";
import Paper from "./paper.svg";
import Library from "./library.svg";
import Triangle from "./triangle.svg";
import Assinatura from "./ImageAboutUs1.svg";
import Detalhes from "./ImageAboutUs2.svg";
import Check from "./check.svg";
import Icon from "./icon.svg";
import XIcon from "./x-icon.svg";

export { Triangle };
export { Assinatura };
export { Detalhes };
export { Newspaper };
export { Key };
export { Paper };
export { Library };
export { Check };
export { Icon };
export { XIcon };
export {Hent_Footer};
export {Facebook};
export {Instagram};
export {Youtube};
export { Hent };
export {IconLosangle};
export {Poligono};